create table venue (
    id bigint generated by default as identity,
    nombre varchar(50) not null,
    direccion varchar(50) not null,
    capacidad integer not null,
    primary key (id)
);

create table event (
    id bigint generated by default as identity,
    nombre varchar(50) not null,
    fecha date not null,
    descripcion varchar(50) not null,
    primary key (id)
);
