alter table event add column venue_id bigint;
alter table event add column deleted boolean default false;

create table categories (
    id bigint generated by default as identity,
    nombre varchar(50) not null,
    primary key (id)
);

create table event_categories (
    event_id bigint not null,
    category_id bigint not null,
    primary key (event_id, category_id)
);

alter table event
    add constraint fk_event_venue
    foreign key (venue_id)
    references venue (id);

alter table event_categories
    add constraint fk_event_categories_event
    foreign key (event_id)
    references event (id);

alter table event_categories
    add constraint fk_event_categories_category
    foreign key (category_id)
    references categories (id);
