alter table event add column venue_id bigint;

alter table event
add column active boolean DEFAULT TRUE;

UPDATE event
SET active = true
WHERE active IS NULL;
ALTER TABLE event
ALTER COLUMN active SET NOT NULL;


create table categories (
    id bigint generated by default as identity,
    name varchar(50) not null,
    description varchar(255),
    primary key (id)
);

create table event_categories (
    event_id bigint not null,
    category_id bigint not null,
    primary key (event_id, category_id)
);

alter table event
    add constraint fk_event_venue
    foreign key (venue_id)
    references venue (id);

alter table event
    alter column venue_id set not null;

alter table event_categories
    add constraint fk_event_categories_event
    foreign key (event_id)
    references event (id);

alter table event_categories
    add constraint fk_event_categories_category
    foreign key (category_id)
    references categories (id);
